{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"User logs in with correct credentials\". Line 15 in scenario \"Unsuccessful checkout\" in the feature \"/Users/naufalazhar/Documents/NAUFAL_AZHAR/BDD_PYTEST/tests/checkout.feature\"\n", "test_name": "test_unsuccessful_checkout", "rerun": "0"}}, "suite_name": "tests/login.py"}}}, "date": "April 09, 2023", "start_time": 1681026224.522225, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}